language:       python
python:
  - "3.5"
before_install:
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
notifications:
     webhooks:  https://chat.bonifacelabs.ca/hooks/7JMEsfq69FGGrs4Mm/BnHezHkBjwDMtTM7ZckmXMWGvS8bF2cpkxizZsscSLxwjS7J
