homeassistant:
  # Name of the location where Home Assistant is running
  name:                                    The Lavado's
  # Location required to calculate the time the sun rises and sets
  latitude:                                !secret homeassistant_latitude
  longitude:                               !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation:                               110
  # metric for Metric, imperial for Imperial
  unit_system:                             metric
  # Pick yours from here:                  http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone:                               America/Toronto

  customize:                               !include customize.yaml
  customize_glob:                          !include customize_glob.yaml

##### HERE COMES THE STUFF! #####

# Enables the frontend, and configuration
frontend:
config:
http:
  ssl_certificate:                         !secret ssl_certificate
  ssl_key:                                 !secret ssl_key
  base_url:                                !secret base_url
updater:
history:
logbook:
logger:
  default:                                 info
  logs:
    homeassistant.components.media_player: error
##### END BASIC BLOCK #####

##### SENSOR BLOCK #####
sun:

sensor:
  - platform:                              yr

## Will restructure later on
 # - platform:                              xbox_live
#    api_key:                               !secret xbox_api_key
#    xuid:                                  !secret xbox_profile
#    scan_interval:                         300

##### END SENSOR BLOCK #####

##### INTERACTION BLOCK #####

##### END INTERACTION BLOCK #####

##### Interfaces Block #####
homekit:
  filter:
    exclude_domains:
      - media_player
ios:
alexa:
    smart_home:
        filter:
            include_domains:
                - script

##### End Interfaces Block #####

##### Physical Control Block #####
# Wink provides Z-Wave/ZigBee services
wink:
lock:
    platform:                              lockitron
    access_token:                          !secret lock_access_token
    id:                                    !secret lock_id
nest:
    client_id:                             !secret nest_client_id
    client_secret:                         !secret nest_client_secret
switch:
    - platform:                            tplink
      host:                                192.168.0.160
##### End Physical Control Block #####

##### Media Block #####
media_player vizio:
  - platform:                              vizio
    host:                                  192.168.0.155
    access_token:                          !secret vizio_token

apple_tv:
  - host:                                  192.168.0.120
    login_id:                              !secret atv1_id
    start_off:                             true
  - host:                                  192.168.0.125
    login_id:                              !secret atv2_id
    start_off:                             true

##### End Media Block #####

##### Automation - The Fun Stuff #####
automation:                                !include automations.yaml
scene:                                     !include scene.yaml
script:                                    !include scripts.yaml
#eventually going to do a !include_dir_merge_named script
##### End Automation #####


group:                                     !include groups.yaml
